# Languages
brew "go"
brew "terraform"

# Containers
brew "colima"
brew "docker"
brew "helm"
brew "k9s"
brew "kubectl"

# Utilities
brew "awscli"
brew "bat"
brew "gnupg"
brew "htop"
brew "jq"
brew "neovim"
brew "ollama"
brew "tmux"
cask "iterm2"

# Applications
cask "firefox"
cask "raycast"
cask "visual-studio-code"
